"""
pages/7_Mesh_Viewer.py
======================
Solid surface mesh viewer for the Human Airways digital twin.

Point cloud vs mesh
-------------------
Every other page in this app renders the airway as ~42,000 floating dots
(a point cloud).  Here the same data is shown as a continuous triangulated
surface — the kind of 3D object that CFD tools, surgical planning software,
and HELYX actually work with.

The mesh is generated by Delaunay 3D triangulation of the point cloud, then
boundary surface extraction (alpha-shape style).  Pre-computed STLs from
scripts/export_mesh.py are loaded directly; otherwise the mesh is built
on-the-fly and cached for the session.
"""

import struct
import sys
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
import streamlit as st
from plotly.subplots import make_subplots

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.data_io import (
    STRIDE,
    load_doe,
    load_pressure_snapshot,
    load_ref_coords,
    load_snapshot_coords,
    get_param_cols,
    PARAM_LABELS,
)
from core.i18n import t, lang_selector

ROOT     = Path(__file__).parent.parent
MESH_DIR = ROOT / "export" / "mesh"

# Probe pyvista availability at import time so the result is definitive
try:
    import pyvista as _pv
    _PYVISTA_OK = True
    _PYVISTA_VERSION = _pv.__version__
except Exception as _e:
    _PYVISTA_OK = False
    _PYVISTA_VERSION = str(_e)

st.set_page_config(page_title="Mesh Viewer", page_icon="🔲", layout="wide")
lang_selector()
st.title(t("mesh_title"))
st.caption(t("mesh_caption"))

if not _PYVISTA_OK:
    st.error(f"pyvista unavailable: {_PYVISTA_VERSION}")
else:
    st.success(f"pyvista {_PYVISTA_VERSION} ready")


# ── Mesh loading / generation ──────────────────────────────────────────────────

def _auto_alpha(pts: np.ndarray) -> float:
    from scipy.spatial import KDTree
    sample = pts[: min(3000, len(pts))]
    d, _   = KDTree(sample).query(sample, k=2)
    return float(np.median(d[:, 1])) * 6.0


def _build_mesh_pyvista(coords: np.ndarray):
    """Point cloud -> (vertices, triangles) via Delaunay 3D."""
    import pyvista as pv
    alpha = _auto_alpha(coords)
    surf  = (
        pv.PolyData(coords.astype(np.float32))
        .delaunay_3d(alpha=alpha)
        .extract_surface(algorithm="dataset_surface")
        .triangulate()
    )
    tris = surf.faces.reshape(-1, 4)[:, 1:]
    return surf.points, tris


@st.cache_data(show_spinner=False)
def get_raw_data(snap: int, stride: int):
    """Return (coords, pressure) — always succeeds, always cached."""
    coords   = load_snapshot_coords(snap, stride)
    pressure = load_pressure_snapshot(snap, stride)
    return coords, pressure


@st.cache_data(show_spinner=False)
def get_mesh_data(snap: int, stride: int):
    """Return (verts, tris, pressure_on_mesh). Raises on failure so result is NOT cached."""
    # Load data directly (avoid calling a cached fn from within a cached fn)
    coords   = load_snapshot_coords(snap, stride)
    pressure = load_pressure_snapshot(snap, stride)

    # 1. Try pre-computed STL
    stl_path = MESH_DIR / f"snapshot_{snap:03d}.stl"
    verts, tris = None, None

    if stl_path.exists():
        try:
            import trimesh
            m     = trimesh.load(str(stl_path))
            verts = np.array(m.vertices, dtype=np.float64)
            tris  = np.array(m.faces)
        except Exception:
            pass

    # 2. Generate on-the-fly — raises if pyvista unavailable (not cached on failure)
    if verts is None:
        verts, tris = _build_mesh_pyvista(coords)

    # 3. Map pressure to mesh vertices via nearest-neighbour
    from scipy.spatial import KDTree
    _, idx           = KDTree(coords).query(verts, k=1)
    pressure_on_mesh = pressure[idx]

    return verts, tris, pressure_on_mesh


# ── Sidebar ────────────────────────────────────────────────────────────────────

with st.sidebar:
    st.header(t("sidebar_settings"))
    snap       = st.slider(t("lbl_snapshot"), 1, 100, 1)
    colorscale = st.selectbox(t("lbl_colour_map"), ["Jet", "Viridis", "RdBu_r", "Plasma"], index=0)
    opacity    = st.slider(t("lbl_opacity"), 0.2, 1.0, 0.85, step=0.05)
    show_cloud = st.checkbox(t("mesh_overlay"), value=False)
    stride_ui  = st.selectbox(t("lbl_resolution"), [50, 20, 10], index=0,
                               help="Lower stride = more nodes = slower render")
    st.divider()
    st.markdown(
        "**Rotate:** left-drag  \n"
        "**Zoom:** scroll  \n"
        "**Pan:** right-drag"
    )
    stl_path = MESH_DIR / f"snapshot_{snap:03d}.stl"
    if stl_path.exists():
        st.success(t("mesh_stl_loaded"))
    else:
        st.info(t("mesh_stl_fly"))


# ── Load data ─────────────────────────────────────────────────────────────────

coords, pressure = get_raw_data(snap, stride_ui)
verts, tris, p_mesh = None, None, None

with st.spinner(f"Loading mesh for snapshot {snap}…"):
    try:
        verts, tris, p_mesh = get_mesh_data(snap, stride_ui)
    except Exception as exc:
        st.warning(f"Mesh generation failed: {exc}. Showing point cloud only.")

# ── Metrics ───────────────────────────────────────────────────────────────────

if verts is not None:
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric(t("mesh_vertices"), f"{len(verts):,}")
    m2.metric(t("mesh_faces"),    f"{len(tris):,}")
    m3.metric(t("met_min_pres"),  f"{p_mesh.min():.1f} Pa")
    m4.metric(t("met_max_pres"),  f"{p_mesh.max():.1f} Pa")
    m5.metric(t("met_delta_p"),   f"{p_mesh.max()-p_mesh.min():.1f} Pa")

# ── Tabs ──────────────────────────────────────────────────────────────────────

tab_mesh, tab_compare, tab_info = st.tabs([
    t("mesh_tab_surface"),
    t("mesh_tab_compare"),
    t("mesh_tab_how"),
])

# ── Tab 1: Mesh ───────────────────────────────────────────────────────────────
with tab_mesh:
    if verts is None:
        # Fallback: show point cloud
        fig = go.Figure(go.Scatter3d(
            x=coords[:, 0], y=coords[:, 1], z=coords[:, 2],
            mode="markers",
            marker=dict(size=2, color=pressure, colorscale=colorscale,
                        colorbar=dict(title="Pressure (Pa)")),
        ))
        st.warning(t("mesh_warn"))
    else:
        traces = [
            go.Mesh3d(
                x=verts[:, 0], y=verts[:, 1], z=verts[:, 2],
                i=tris[:, 0],  j=tris[:, 1],  k=tris[:, 2],
                intensity=p_mesh,
                colorscale=colorscale,
                colorbar=dict(title="Pressure (Pa)", thickness=14),
                opacity=opacity,
                lighting=dict(ambient=0.5, diffuse=0.8,
                              specular=0.3, roughness=0.5, fresnel=0.2),
                lightposition=dict(x=1000, y=1000, z=500),
                hovertemplate="P: %{intensity:.1f} Pa<extra></extra>",
                name="Airway surface",
            )
        ]
        if show_cloud:
            traces.append(go.Scatter3d(
                x=coords[:, 0], y=coords[:, 1], z=coords[:, 2],
                mode="markers",
                marker=dict(size=1, color="rgba(180,180,180,0.3)"),
                hoverinfo="skip",
                name="Point cloud",
            ))

        fig = go.Figure(traces)

    fig.update_layout(
        scene=dict(
            aspectmode="data",
            bgcolor="rgb(12,14,20)",
            xaxis=dict(title="X (m)", gridcolor="#2a2a2a", showbackground=False),
            yaxis=dict(title="Y (m)", gridcolor="#2a2a2a", showbackground=False),
            zaxis=dict(title="Z (m)", gridcolor="#2a2a2a", showbackground=False),
        ),
        paper_bgcolor="rgb(12,14,20)",
        font=dict(color="white"),
        height=650,
        margin=dict(l=0, r=0, b=0, t=30),
        title=f"Snapshot {snap} — Solid Surface Mesh (pressure coloured)",
    )
    st.plotly_chart(fig, use_container_width=True)

    # STL download
    if stl_path.exists():
        st.download_button(
            label=t("mesh_dl_stl"),
            data=stl_path.read_bytes(),
            file_name=f"airway_snapshot_{snap:03d}.stl",
            mime="application/octet-stream",
            help="Open in MeshLab, Blender, HELYX, or any 3D tool.",
        )
    else:
        st.caption(
            "Run `python scripts/export_mesh.py` to pre-generate all 100 STL files. "
            "Current mesh was generated on-the-fly and is not persisted."
        )


# ── Tab 2: Comparison ─────────────────────────────────────────────────────────
with tab_compare:
    st.markdown(
        "**Left:** original point cloud (dots) — what every other page shows.  \n"
        "**Right:** surface mesh (solid) — what CFD tools and HELYX work with."
    )

    fig2 = make_subplots(
        rows=1, cols=2,
        specs=[[{"type": "scene"}, {"type": "scene"}]],
        subplot_titles=["Point Cloud (scatter3d)", "Surface Mesh (Mesh3d)"],
    )

    # Point cloud
    fig2.add_trace(
        go.Scatter3d(
            x=coords[:, 0], y=coords[:, 1], z=coords[:, 2],
            mode="markers",
            marker=dict(size=1.5, color=pressure, colorscale=colorscale,
                        colorbar=dict(title="Pa", x=0.42, thickness=10)),
            hovertemplate="P: %{marker.color:.1f} Pa<extra></extra>",
            name="Point cloud",
        ),
        row=1, col=1,
    )

    # Mesh
    if verts is not None:
        fig2.add_trace(
            go.Mesh3d(
                x=verts[:, 0], y=verts[:, 1], z=verts[:, 2],
                i=tris[:, 0],  j=tris[:, 1],  k=tris[:, 2],
                intensity=p_mesh,
                colorscale=colorscale,
                colorbar=dict(title="Pa", x=1.01, thickness=10),
                opacity=0.9,
                lighting=dict(ambient=0.5, diffuse=0.8, specular=0.2),
                name="Surface mesh",
            ),
            row=1, col=2,
        )
    else:
        fig2.add_annotation(
            text="Mesh not available", xref="paper", yref="paper",
            x=0.75, y=0.5, showarrow=False, font=dict(color="white", size=14),
        )

    scene_style = dict(
        bgcolor="rgb(12,14,20)",
        xaxis=dict(showbackground=False, gridcolor="#333"),
        yaxis=dict(showbackground=False, gridcolor="#333"),
        zaxis=dict(showbackground=False, gridcolor="#333"),
        aspectmode="data",
    )
    fig2.update_layout(
        scene=scene_style, scene2=scene_style,
        paper_bgcolor="rgb(12,14,20)",
        font=dict(color="white"),
        height=580,
        margin=dict(l=0, r=0, b=0, t=50),
    )
    st.plotly_chart(fig2, use_container_width=True)

    st.info(
        "The point cloud has no connectivity — it is just a bag of coordinates. "
        "The mesh connects those same points into triangles, giving a continuous "
        "watertight surface that boundary conditions and mesh refinement can be applied to."
    )


# ── Tab 3: Info ───────────────────────────────────────────────────────────────
with tab_info:
    c1, c2 = st.columns(2)

    with c1:
        st.subheader(t("mesh_sub_how"))
        st.markdown("""
        #### What the Twin Builder outputs

        Ansys Twin Builder exports **nodal data**: 2,135,906 (x, y, z) points — the nodes
        of the finite element mesh used for the CFD simulation. No face connectivity is
        stored in the `.bin` files. That gives us a *point cloud*, not a mesh.

        #### How we reconstruct the surface

        1. **Delaunay 3D triangulation** — fills the point cloud with tetrahedra
        2. **Boundary extraction** — keeps only the faces on the outer surface
        3. **Alpha-shape filtering** — the `alpha` parameter controls how tightly the
           mesh wraps concave regions (airways are tubular, so a tight alpha is needed)

        #### Alpha value

        Estimated automatically from the median nearest-neighbour spacing in the
        point cloud:

        ```
        alpha = median_nn_distance × 6
        ```

        At stride = 50 (42K nodes), median spacing is ~1.4 mm → alpha ~8.4 mm.
        """)

    with c2:
        st.subheader(t("mesh_sub_quality"))
        st.markdown("""
        #### Resolution vs quality trade-off

        | Stride | Nodes | Time per mesh | Mesh quality |
        |--------|-------|---------------|--------------|
        | 50     | ~42K  | ~2 s          | Good for VR and teaching |
        | 10     | ~214K | ~8 s          | Better detail at bronchi  |
        | 1      | 2.1M  | ~120 s        | Full resolution           |

        #### Limitations

        - The mesh is a **surface reconstruction**, not the original FEM mesh. Fine
          details at very narrow regions (glottis, small bronchi) may be smoothed.
        - The surface is **watertight** — inlet/outlet openings are closed. HELYX
          engineers cut these open and assign boundary conditions.
        - For the 1000 virtual shapes, geometry is POD-reconstructed at stride = 50,
          so surface detail is limited to the modes captured by the training data.

        #### What HELYX does next

        ```
        STL → snappyHexMesh → OpenFOAM PolyMesh → CFD simulation
        ```

        The STL is just the starting point. HELYX re-meshes it with a structured
        hexahedral grid, then solves the Navier-Stokes equations.
        """)

        if verts is not None:
            st.metric(t("mesh_sub_compress"),
                      f"{len(coords):,} pts → {len(tris):,} faces",
                      help="Each triangular face implicitly encodes 3 point connections")
