"""Compute simple proxy physics metrics for a predicted airway.

These metrics are not real CFD results. They are simplified indicators that can
be useful in a digital twin interface when we want quick geometry and pressure
summaries without running a full fluid simulation.
"""

# This import enables modern type-hint behavior.
from __future__ import annotations

# Path gives clean filesystem path handling.
from pathlib import Path

# NumPy loads predictions and computes numerical metrics.
import numpy as np

# pandas saves the final metrics table as CSV.
import pandas as pd


# PROJECT_ROOT points to the main project folder, one level above scripts/.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

# PREDICTIONS_DIR points to generated prediction files.
PREDICTIONS_DIR = PROJECT_ROOT / "outputs" / "predictions"

# GEOMETRY_PATH is the predicted geometry field generated by script 06.
GEOMETRY_PATH = PREDICTIONS_DIR / "predicted_geometry_row0.npy"

# PRESSURE_PATH is the predicted pressure field generated by script 06.
PRESSURE_PATH = PREDICTIONS_DIR / "predicted_pressure_row0.npy"

# OUTPUT_PATH is where the proxy physics metrics will be saved.
OUTPUT_PATH = PREDICTIONS_DIR / "proxy_physics_row0.csv"

# SMALL_EPSILON prevents division by zero in the resistance proxy.
SMALL_EPSILON = 1e-12


def load_prediction(path: Path, label: str) -> np.ndarray | None:
    # If the prediction file is missing, print a warning and return None.
    if not path.exists():
        print(f"WARNING: Missing {label} prediction file: {path}")
        return None

    # Load the prediction from the .npy file.
    values = np.load(path)

    # Convert to float64 for stable metric calculations.
    values = np.asarray(values, dtype=np.float64)

    # Print the loaded shape for diagnostics.
    print(f"Loaded {label} prediction with shape {values.shape}.")

    # Return the loaded prediction array.
    return values


def reshape_geometry_to_points(geometry: np.ndarray | None) -> np.ndarray | None:
    # If geometry is missing, no geometry metrics can be computed.
    if geometry is None:
        return None

    # Flatten the geometry so we can check whether it forms x, y, z triples.
    flat = geometry.ravel()

    # If the flattened geometry is divisible by 3, reshape it to N x 3 points.
    if flat.size % 3 == 0:
        points = flat.reshape(-1, 3)
        print(f"Geometry reshaped to point cloud with shape {points.shape}.")
        return points

    # If there is one leading header-like value, try skipping it.
    if flat.size > 1 and (flat.size - 1) % 3 == 0:
        points = flat[1:].reshape(-1, 3)
        print(f"Geometry reshaped after skipping one leading value with shape {points.shape}.")
        return points

    # If neither case works, print a helpful diagnostic.
    print(f"WARNING: Geometry has {flat.size} values and cannot be reshaped to (-1, 3).")
    return None


def compute_geometry_metrics(points: np.ndarray | None) -> dict[str, float]:
    # Start with an empty metric dictionary.
    metrics: dict[str, float] = {}

    # If points are unavailable, return no geometry metrics.
    if points is None:
        return metrics

    # Compute the minimum x, y, z coordinates of the bounding box.
    bbox_min = np.min(points, axis=0)

    # Compute the maximum x, y, z coordinates of the bounding box.
    bbox_max = np.max(points, axis=0)

    # Compute the centroid, which is the average point location.
    centroid = np.mean(points, axis=0)

    # Compute the width in x direction.
    width_x = bbox_max[0] - bbox_min[0]

    # Compute the width in y direction.
    width_y = bbox_max[1] - bbox_min[1]

    # Compute the vertical extent in z direction.
    vertical_extent = bbox_max[2] - bbox_min[2]

    # Compute each point's radial distance from the centroid in the xy plane.
    radial_distances = np.sqrt((points[:, 0] - centroid[0]) ** 2 + (points[:, 1] - centroid[1]) ** 2)

    # Compute a simplified average radius proxy.
    mean_radius_proxy = float(np.mean(radial_distances))

    # Compute a simplified minimum radius proxy.
    min_radius_proxy = float(np.min(radial_distances))

    # Compute a simplified maximum radius proxy.
    max_radius_proxy = float(np.max(radial_distances))

    # Compute a constriction indicator; lower values suggest stronger narrowing.
    constriction_index = min_radius_proxy / mean_radius_proxy if mean_radius_proxy > 0 else np.nan

    # Store bounding box minimum values.
    metrics["bbox_min_x"] = float(bbox_min[0])
    metrics["bbox_min_y"] = float(bbox_min[1])
    metrics["bbox_min_z"] = float(bbox_min[2])

    # Store bounding box maximum values.
    metrics["bbox_max_x"] = float(bbox_max[0])
    metrics["bbox_max_y"] = float(bbox_max[1])
    metrics["bbox_max_z"] = float(bbox_max[2])

    # Store geometric extents.
    metrics["vertical_extent"] = float(vertical_extent)
    metrics["width_x"] = float(width_x)
    metrics["width_y"] = float(width_y)

    # Store centroid coordinates.
    metrics["centroid_x"] = float(centroid[0])
    metrics["centroid_y"] = float(centroid[1])
    metrics["centroid_z"] = float(centroid[2])

    # Store radius proxy metrics.
    metrics["mean_radius_proxy"] = mean_radius_proxy
    metrics["min_radius_proxy"] = min_radius_proxy
    metrics["max_radius_proxy"] = max_radius_proxy
    metrics["constriction_index"] = float(constriction_index)

    # Return all geometry metrics.
    return metrics


def compute_pressure_metrics(pressure: np.ndarray | None) -> dict[str, float]:
    # Start with an empty metric dictionary.
    metrics: dict[str, float] = {}

    # If pressure is unavailable, return no pressure metrics.
    if pressure is None:
        return metrics

    # Flatten pressure so all values are treated as scalar samples.
    values = pressure.ravel()

    # If no pressure values exist, return no pressure metrics.
    if values.size == 0:
        print("WARNING: Pressure prediction is empty.")
        return metrics

    # Compute minimum predicted pressure.
    pressure_min = float(np.min(values))

    # Compute maximum predicted pressure.
    pressure_max = float(np.max(values))

    # Store pressure metrics.
    metrics["pressure_min"] = pressure_min
    metrics["pressure_max"] = pressure_max
    metrics["pressure_mean"] = float(np.mean(values))
    metrics["pressure_std"] = float(np.std(values))
    metrics["pressure_range"] = float(pressure_max - pressure_min)

    # Return all pressure metrics.
    return metrics


def add_proxy_outputs(metrics: dict[str, float]) -> None:
    # Read the mean radius proxy if geometry metrics were available.
    mean_radius = metrics.get("mean_radius_proxy")

    # If mean radius exists, estimate flow capacity using a radius^4 relationship.
    if mean_radius is not None and np.isfinite(mean_radius):
        metrics["flow_capacity_proxy"] = float(mean_radius**4)

    # If mean radius is missing, flow capacity cannot be estimated.
    else:
        metrics["flow_capacity_proxy"] = np.nan

    # Read the flow capacity proxy.
    flow_capacity = metrics["flow_capacity_proxy"]

    # Compute resistance as the inverse of flow capacity, protected by epsilon.
    if np.isfinite(flow_capacity):
        metrics["resistance_proxy"] = float(1.0 / max(flow_capacity, SMALL_EPSILON))

    # If flow capacity is unavailable, resistance is unavailable.
    else:
        metrics["resistance_proxy"] = np.nan

    # If pressure range exists, use it as the pressure drop proxy.
    if "pressure_range" in metrics:
        metrics["pressure_drop_proxy"] = metrics["pressure_range"]

    # Otherwise use resistance as a fallback simplified pressure-drop proxy.
    else:
        metrics["pressure_drop_proxy"] = metrics["resistance_proxy"]


def print_metrics(metrics: dict[str, float]) -> None:
    # Print a clear title before listing metrics.
    print("\nProxy physics metrics:")

    # Print every metric name and value on its own line.
    for key, value in metrics.items():
        print(f"  {key}: {value}")


def main() -> None:
    # Load predicted geometry if available.
    geometry = load_prediction(GEOMETRY_PATH, "geometry")

    # Load predicted pressure if available.
    pressure = load_prediction(PRESSURE_PATH, "pressure")

    # Try to reshape predicted geometry into N x 3 point coordinates.
    points = reshape_geometry_to_points(geometry)

    # Compute geometry-based proxy metrics.
    metrics = compute_geometry_metrics(points)

    # Add pressure-based proxy metrics.
    metrics.update(compute_pressure_metrics(pressure))

    # Add simplified flow, resistance, and pressure-drop proxy outputs.
    add_proxy_outputs(metrics)

    # Print all metrics clearly.
    print_metrics(metrics)

    # Make sure the predictions output folder exists.
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Save metrics as one-row CSV table.
    pd.DataFrame([metrics]).to_csv(OUTPUT_PATH, index=False)

    # Print where the CSV report was saved.
    print(f"\nSaved proxy physics metrics to: {OUTPUT_PATH}")


# This makes main() run only when this file is executed directly.
if __name__ == "__main__":
    main()
