"""Compute simple proxy physics metrics for a predicted airway.

These metrics are not real CFD results. They are simplified indicators that can
be useful in a digital twin interface when we want quick geometry and pressure
summaries without running a full fluid simulation.
"""

# This import enables modern type-hint behavior.
from __future__ import annotations

# sys lets this script add src/ to Python's import path when run from scripts/.
import sys

# Path gives clean filesystem path handling.
from pathlib import Path

# pandas saves the final metrics table as CSV.
import pandas as pd


# Add src/ to the import path so this numbered script can use shared helpers.
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

# Import shared binary helper for reshaping geometry into points.
from airways.binary import reshape_values_to_points

# Import shared prediction loading helper.
from airways.io import load_prediction

# Import shared project paths.
from airways.paths import PREDICTIONS_DIR

# Import shared proxy metric calculation.
from airways.proxy_physics import compute_proxy_metrics


# GEOMETRY_PATH is the predicted geometry field generated by script 06.
GEOMETRY_PATH = PREDICTIONS_DIR / "predicted_geometry_row0.npy"

# PRESSURE_PATH is the predicted pressure field generated by script 06.
PRESSURE_PATH = PREDICTIONS_DIR / "predicted_pressure_row0.npy"

# OUTPUT_PATH is where the proxy physics metrics will be saved.
OUTPUT_PATH = PREDICTIONS_DIR / "proxy_physics_row0.csv"


def print_metrics(metrics: dict[str, float]) -> None:
    # Print a clear title before listing metrics.
    print("\nProxy physics metrics:")

    # Print every metric name and value on its own line.
    for key, value in metrics.items():
        print(f"  {key}: {value}")


def main() -> None:
    # Load predicted geometry if available.
    geometry = load_prediction(GEOMETRY_PATH, "geometry")

    # Load predicted pressure if available.
    pressure = load_prediction(PRESSURE_PATH, "pressure")

    # Try to reshape predicted geometry into N x 3 point coordinates.
    points, geometry_status = reshape_values_to_points(geometry)

    # Print reshape diagnostics so the user knows whether geometry metrics are available.
    print(f"Geometry reshape status: {geometry_status}")

    # Compute geometry, pressure, flow, resistance, and pressure-drop proxy outputs.
    metrics = compute_proxy_metrics(points, pressure)

    # Print all metrics clearly.
    print_metrics(metrics)

    # Make sure the predictions output folder exists.
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Save metrics as one-row CSV table.
    pd.DataFrame([metrics]).to_csv(OUTPUT_PATH, index=False)

    # Print where the CSV report was saved.
    print(f"\nSaved proxy physics metrics to: {OUTPUT_PATH}")


# This makes main() run only when this file is executed directly.
if __name__ == "__main__":
    main()
